# Generated by Django 3.1.5 on 2021-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0004_clothing_electronics_grocery_household_sports_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
