# Generated by Django 3.1.5 on 2021-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0006_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
