# Generated by Django 3.1.5 on 2021-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0010_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
    ]
