# Generated by Django 3.1.5 on 2021-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0011_auto_20210427_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
        migrations.AddField(
            model_name='household',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
        migrations.AddField(
            model_name='sports',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='img',
            field=models.ImageField(default='Ghantdi!!', upload_to='ksi_store/'),
        ),
    ]
